Huddly/sdk

- package.json
> Version 0.1.0

- README.md
- package-lock.json
- package.json
- src/components/detector.ts
- src/interfaces/IDetectorOpts.ts
Make it possible to configure the autoframing when initializing the detector!
> Configure Autoframe!

- src/components/detector.ts
- src/interfaces/IDetectorOpts.ts
- src/utilitis/framingconfig.ts
It should be possible to switch between enabling/disabling autoframing without having to power-cycle the camera.
> Framing Config Update

- package-lock.json
- package.json
This reverts commit fc819497089b45e65847f238ee72b6a111155d5c.
> Revert "0.1.15"

- src/components/upgrader/hpkUpgrader.ts
Also, limit status printing to max 1msg/s during upgrade
> hpkUpgrader: Fix issue where status goes 100->0->100

- src/components/upgrader/boxfishUpgraderFactory.ts
> boxfish upgrade: Adding override of HPK_SUPPORT_VERSION via env variable

- package-lock.json
- package.json
Fixing broken pretty check-in master and rerelease
> New version of sdk and linter fix

- src/components/device/factory.ts
- src/index.ts
Support boxfish production application and export SDK API for gaining access to static functions
> Users/geir t/testing/multidevice

- docs/contributing.html
- docs/dependencies.html
- docs/index.html
- docs/interfaces/IDetector.html
- docs/interfaces/UpgradeOpts.html
- docs/js/menu-wc.js
- package-lock.json
- src/components/detector.ts
- src/interfaces/IDetector.ts
- tests/components/detector.spec.ts
Detector.ts: Update the detector class by refactoring the start/stop functions into enable, disable, start and stop based on what their specific action is.
> Detector.ts Update/Refactor

- src/components/device/boxfish.ts
For use in production: need to be able to flash the first stage bootloader.
> Added fsbl upgrade to boxfish

- CONTRIBUTING.md
Compared new and old and found no issues with the styling.
> docs(CONTRIBUTING.md): Bumped version of compodoc

- src/components/device/factory.ts
See https://github.com/Huddly/kubicam-sw/pull/298 for context
> Add "dummy" camera mode using product id 0x0061

- src/components/api.ts
- src/components/device/boxfish.ts
file-transfer is not supported by recent boxfish releases.
> feat(getErrorLog): Add option for disallowing legacy mode

- package-lock.json
- package.json
- src/components/device/ace.ts
- tests/components/device/ace.spec.ts
Add support for ACE -> Reset Settings (Default)
> L1 reset settings

- package-lock.json
- package.json
- src/components/autozoomControl.ts
- tests/components/autozoomControl.spec.ts
First draft for supporting gallery view.
> feat: Support new autozoom mode 'Plaza' (aka 'Gallery View') on IQ

- package-lock.json
- package.json
- src/components/ipDetector.ts
- src/components/upgrader/aceUpgrader.ts
- src/components/upgrader/hpkUpgrader.ts
- tsconfig.json
Addresses a vulnerability present in current jszip version.
Had to do a few small changes to tsconfig and code to make it compile.
I see that we have a lock on version for jszip, and I guess it might be for a good reason, but I am unable to spend more time on this for now, so consider this a suggestion.
> chore(package.json): updated jszip dependency

- package-lock.json
- package.json
Tend to all the security vulnerabilities on sdk.
> fix: vulnerabilities & remove cz-conventional-changelog

- .github/workflows/build.yml
- package-lock.json
- package.json
- scripts/checkVulnerabilities.js
This change introduces dependency audit checks when submitting pull requests on github. Motivation behind this change is to avoid introducing dependency vulnerabilities into master for future changes but also if new vulnerabilities are detected developers wont be able to introduce new changes before those vulnerabilities are fixed.
> Audit check

- .github/workflows/build.yml
- Cron trigger master branch build workflow every day at 0700
- Send slack notification if the `Build & Test` job fails
> feat: Cron trigger master branch

- src/components/autozoomControl.ts
- tests/components/autozoomControl.spec.ts
Cannot call setMode on a camera running a firmware where this feature is
not supported (was introduced with the Plaza support). The fix involves
making the options "mode" to defaul to 'NORMAL' which means the camera
is in autozoom (GF) mode by default.
Adding additional tests for testing all the edge cases when updating the
autozoom control options.
> bugfix: Init & setMode should be backward-compatible

- package-lock.json
- package.json
Kristians hotfix was merged into the official repo.
> build: bump cpio-stream

- src/components/upgrader/ipUpgrader.ts
This is meant as a low risk effort to make the upgrader work with the new cpio files used for the ip cameras. In the future we should address how we read and process cpio files and make sure to support the new image format. For now the following has been done.
* Added additional timeout
* Using cpio-reader callback to progress also when going through unused files
> fix(ipUpgrader): fix bug where upgrader is unable to use new cpio files
