Huddly/sdk

package-lock.json, package.json, src/components/detector.ts
Updating detector.ts script to use axios as the library for downloading the detector blob and config instead of node-fetch. Although mentioned on their github page, node-fetch does not seem to work when running detection directly on browser. Also added additional framing information to the detections object emitted by the detector.
=> Node-Fetch -> Axios

examples/rest/README.md, examples/rest/package.json, examples/rest/yarn.lock
Update dependencies on rest example! Change the engnine restriction on the rest example to be greater than 8.9.4 (updated the eslint dev dependencies to be compatible with node 8.9.4 and greater).
=> Update Rest Example to use latest SDK and Device Api

package-lock.json, package.json, src/components/detector.ts, src/interfaces/IDetectorOpts.ts, tests/components/detector.spec.ts
Fixing a regression bug on detector init. AUTO_PTZ should be set in case the shouldAutoFrame option is provided as detector opts. The bug was that when this option was provided, it always set the auto_ptz to false even though the shouldAutoFrame option could have been `true`.
=> `shouldAutoFrame` regression bugfix

README.md, docs/index.html
There was a typo for the link to `nvm` setup. That is all.
=> README.md typo on `nvm` link

src/components/device/boxfish.ts, tests/components/device/boxfish.spec.ts
When booting the camera into mvusb mode, no reply message is being sent back. That is because after sending `upgrader/mv_usb` message, the camera proceeds to boot and re-enumerate into a custom usb device and any attempt to communicate with the device as Huddly IQ will fail. The fix is to just do a "fire and forget" type of message and then from the caller, check that the device has enumerated on the proper mode.
=> Camera mode boot bugfix

src/components/upgrader/hpkUpgrader.ts, src/interfaces/IUpgradeOpts.ts, tests/components/upgrader/hpkUpgrader.spec.ts
In production we will be using boxfish-prod.hpk that flashes to the C image. The SDK checks for a successful upgrade by testing if the CNN has loaded properly, but the CNN is disabled when booting from the C/factory image. 
If the production_upgrade flag is set then the upgrader will accept the boxfish-production.hpk.
=> production: HpkUpgrader to handle boxfish-prod.hpk

src/components/device/boxfish.ts
I want to expose the usb location(e.g. 2-1.3.1) given by device-api-usb. To be used in production.
=> Adding location to getInfo results

docs/additional-documentation/peoplecount-in-a-meeting-room.html, docs/interfaces/IDeviceManager.html, docs/miscellaneous/enumerations.html, package-lock.json, package.json, src/components/api.ts, src/components/device/boxfish.ts, src/components/device/huddlygo.ts, src/interfaces/ReleaseChannelEnum.ts, src/interfaces/iDeviceManager.ts, tests/components/api.spec.ts, tests/components/device/boxfish.spec.ts, tests/mocks/devicemanager.mock.ts
Use the SDK to find out what is the latest released firmware for any huddly device (GO and IQ for
now). Based on what device is plugged into your machine, calling `getLatestFirmwareUrl` will return
the url to the firmware package for the provided release channel (which by default is the "stable"
channel)
=> feat(DeviceManager): Get url for latest released firmware for huddly device

src/components/device/factory.ts
Since uvc control interface is not supported on the open source version of the sdk, logging warnings
that none of the device api's do not support uvc control interface is redundant.
=> refactor(Factory.ts): Remove confusing warning logs on factory class

src/components/api.ts
When calling getErrorLog recursively after it failed the first time, we need to make sure we are
passing the exact same parameters as the original call (with exception of the retry parameter which of course will be subtracted for each call as it is the termination logic for the recursion).
=> fix(api.ts): getErrorLog recursive call with exact parameters

huddlyproto/package-lock.json, huddlyproto/package.json, huddlyproto/proto/win_service.proto, package-lock.json, package.json, src/components/service/factory.ts, src/components/service/winIpCameraService.ts, src/index.ts, src/interfaces/IHuddlyService.ts, src/interfaces/IServiceOpts.ts, src/interfaces/IWinServiceModels.ts, tests/components/service/factory.spec.ts, tests/components/service/winIpCameraService.spec.ts, tests/sdk.spec.ts
- Import service proto file (currently a temporary solution as this should move to falcon-interface)
- Bumped and released new version of @huddly/huddlyproto
- Implemented all the Huddly Windows Service features described on the protofile through SDK api calls
- Boilerplate code for describing Huddly services
- Unit Testing of the new functionality
=> L1 service proto

src/components/device/ace.ts, tests/components/device/ace.spec.ts
- We should be able to get information such as deviceId directly from the ace device object
- getState should output some form of state. For now it's just autuzoom status
=> Support in electron-app

src/components/upgrader/aceUpgrader.ts, src/interfaces/IUpgradeOpts.ts, src/utilitis/bufferStream.ts, tests/components/upgrader/aceUpgrader.spec.ts, tests/utilities/bufferStream.spec.ts
- Fix ace upgrader to accept a filer buffer instead of file path
- Fix ace upgrade progress status events (better distribution of the percentages on each stage)
- Starting a nodejs time interval emitting progress events whilst the camera is booting up
=> Ace upgrade filebuffer support

src/components/device/factory.ts
This should reflect the indeded decimal value which is 1001 for L1. Output:
```
{
name: 'L1',
mac: '90:E2:FC:90:12:EC',
ipv4: '169.254.98.175',
serialNumber: '12101A0029',
modelName: '810-00011-MBLK',
manufacturer: 'Huddly',
productId: 1001, // ,<---------------------- UPDATED INFORMATION
version: '1.2.5-4035.13+sha.bf526c3',
uptime: 32.26,
slot: 'B'
}
```
=> fix: Update L1 pid from 3E9 to 0x3E9

src/components/device/factory.ts
This will be imported by device-api-* instead of hardcoding the value in several places
=> refactor: Export huddly vendor id on factory.ts

src/index.ts, tests/sdk.spec.ts
The try...catch block inside a promise on sdk#setupDeviceDiscoveryListeners for the ATTACH event should be resolved for both cases when the try succeeds or the catch is invoked. This scenario was initiation when a BASE device was discovered and no transport implementation is supported for it so we ended up in the catch block and were not able to complete the execution of the block due to the promise not being marked as completed. Fix was to just add `resolve()` at the end of the catch block.
=> bugfix: Avoid discovery hang for BASE

examples/canvas_doc/canvas.md, examples/canvas_doc/index.js, examples/canvas_doc/package-lock.json, examples/canvas_doc/package.json, examples/summary.json, package-lock.json, src/components/device/ace.ts, src/components/device/boxfish.ts, src/components/device/dartfish.ts, src/components/device/dwarffish.ts, src/components/device/factory.ts, src/components/device/huddlygo.ts, tests/components/device/ace.spec.ts, tests/components/device/dartfish.spec.ts, tests/components/device/dwarffish.spec.ts, tests/components/device/factory.spec.ts
- Add support for Canvas on SDK
- Refactor Dwarfish and Dartfish supported methods
- Dartfish supports sw upgrade
- Dwarfish supports sw upgrade and cnn facebasedexposure feature
- Audit dependencies
TODO:
=> Canvas Support & Refactoring

package-lock.json, package.json, src/components/service/cameraSwitchService.ts, src/interfaces/ICameraSwitchModels.ts, tests/components/service/cameraSwitchService.spec.ts
This version removes the "mac" field of the proto definition which is
not required anymore by the windows service
=> chore: update @huddly/camera-switch-proto@0.0.4

src/components/ipDetector.ts, tests/components/ipDetector.spec.ts
Previsouly the setCnnFeature was invoked with the START mode instead of
STOP as it should be.
=> fix(ipdetector.ts): _stopDetections should invoke setCnnFeature with the correct mode

src/components/ipDetector.ts
For ...reasons, falcon-app will send out a message with 
`detectionsList: [ { id: 0, label: "NULL", ... } ]`
For situations where the camera does not detect any people on the frame.
With the previous implementation, this would be emitted in the RAW_DETECTIONS event. This little thing fixes that, but obviously this should be fixed camera side in the long run.
=> fix: temporary workaround for not emitting dummy rawDetections

src/components/device/ace.ts, src/components/ipDetector.ts
This is to avoid any unfortunate cases of undefined being passed as a return value
=> fix: added return statement after reject in ace.ts & ipDetector.ts

package.json
that fixes a bug in the officia npm package which makes it incompatible with newer versions of js
This is perhaps not the right way to do it .. i have no clue..
=> depend on huddly fork of cpio-stream

src/components/device/ace.ts
Some of the added return statements are redundant, but I just added them as a fail safe if code was to be added after the catch blocks later.
=> fix(ace): add return after reject where missing

package-lock.json, package.json, src/components/api.ts, src/components/upgrader/boxfishUpgrader.ts, tests/components/api.spec.ts, tests/components/device/factory.spec.ts
This PR removes all the async file transfer code that was used way back for upgrading and fetching error log. I.e. all the legacy methods that used asyncFileTransfer are deleted.
=> Remove legacy async filetransfer code

src/index.ts
In case we get an exception/error while initializing a new device, we are emitting an 'ERROR' event on the discovery emitter. However, the payload of this event does not contain the actual error message/stacktrace. So, this PR takes care of that :)
=> feat: on getDevice error, emit stacktrace

src/components/upgrader/boxfishUpgrader.ts, src/components/upgrader/hpkUpgrader.ts, tests/components/upgrader/hpkUpgrader.spec.ts
Should maybe be done through a more extensive refactoring..?
=> fix: hotfix for dartfish upgrader crashing when verifying upgrade

package-lock.json, src/utilitis/bufferStream.ts
Previous implementation had the wrong return type (according to the Readable interface).
I considered throwing an error if trying to call destroy on an instance that has already been destroyed, so I checked the behaviour of the stream provided by node:fs' createReadStream. It did not throw - so let's  keep it like this.
=> fix: bufferStream now correctly implements destroy method
